title: Workshop on Urban Recommender Systems
logo: /assets/img/logo.png
description: First Workshop on Urban Recommender Systems held in conjunction with the 2024 ACM Conference on Recommender Systems.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
